### ISSUE TITLE
compilation and run on linux for OSVR-HMD 

### ISSUE THREAD

**Issue by Olm-e** [OSVR/OSVR-Core#432] opened 2016-05-02 14:01 UTC
hello,
trying to compile and run the master branch on linux,
had to comment some parameters in com_osvr_Multiserver.cpp (line 146) to make it compile (see pull request),
but now, it does'nt run and throw a regex error

`vr bin # ./osvr_server osvr_server_config.HDK12ExtendedLandscape.sample.json
[OSVR Server] Using config file 'osvr_server_config.HDK12ExtendedLandscape.sample.json'
[OSVR Server] Constructing server as configured...
[OSVR Server] Loading auto-loadable plugins...
[OSVR Server] Loading plugins...
[OSVR Server] 
[OSVR Server] Instantiating configured drivers...
[OSVR] Added device: org_osvr_filter_videoimufusion/HeadFusion
[OSVR] Client context initialized for org.osvr.analysisplugin
[OSVR Server] Successes:
[OSVR Server]  - com_osvr_VideoBasedHMDTracker/VideoBasedHMDTracker
[OSVR Server] 
[OSVR Server] Errors:
[OSVR Server]  - org_osvr_filter_videoimufusion/VideoIMUFusion	regex_error
[OSVR Server] 
[OSVR Server] 
[OSVR Server] Aliases found and parsed from config file.
[OSVR Server] Display descriptor found and parsed from config file.
[OSVR Server] RenderManager config found and parsed from the config file.
[OSVR Server] Triggering automatic hardware detection...
[OSVR Server] Registering shutdown handler...
[OSVR Server] Starting server mainloop: OSVR Server is ready to go!
[OSVR] Performing hardware auto-detection.
[OSVR] Added device: com_osvr_Multiserver/OSVRHackerDevKit0
terminate called after throwing an instance of 'std::regex_error'
  what():  regex_error
Aborted
vr bin # ^C
vr bin # ./osvr_server OSVR_HDK_1_3.json 
[OSVR Server] Using config file 'OSVR_HDK_1_3.json'
[OSVR Server] Constructing server as configured...
[OSVR Server] Loading auto-loadable plugins...
[OSVR Server] Loading plugins...
[OSVR Server] 
[OSVR Server] Instantiating configured drivers...
[OSVR Server] 
[OSVR Server] Using OSVR HDK for display configuration. Did not find an alternate valid 'display' object in config file.
[OSVR Server] Triggering automatic hardware detection...
[OSVR Server] Registering shutdown handler...
[OSVR Server] Starting server mainloop: OSVR Server is ready to go!
[OSVR] Performing hardware auto-detection.
[OSVR] Added device: com_osvr_Multiserver/OSVRHackerDevKit0
terminate called after throwing an instance of 'std::regex_error'
  what():  regex_error
Aborted`

any hint ?
is there anyone that had the video tracker working on linux ? (I have some serious projects waiting for this to be ported to the OSVR-HMD)
thanks a lot !

**Comment by cobbchaseRazer** [comment] 2016-05-20 17:42
Same issue here. 

> commit 0c54f5eac5b24490ac547f548812dd731911e238  

> sudo osvr_server /usr/local/share/osvrcore/osvr_server_config.json
> [OSVR Server] Using config file '/usr/local/share/osvrcore/osvr_server_config.json'
> [OSVR Server] Constructing server as configured...
> [OSVR Server] Loading auto-loadable plugins...
> [OSVR Server] Loading plugins...
> [OSVR Server] 
> [OSVR Server] Instantiating configured drivers...
> [OSVR Server] 
> [OSVR Server] Using OSVR HDK for display configuration. Did not find an alternate valid 'display' object in config file.
> [OSVR Server] Triggering automatic hardware detection...
> [OSVR Server] Registering shutdown handler...
> [OSVR Server] Starting server mainloop: OSVR Server is ready to go!
> [OSVR] Performing hardware auto-detection.
> [OSVR] Added device: com_osvr_Multiserver/OSVRHackerDevKit0
> terminate called after throwing an instance of 'std::regex_error'
>   what():  regex_error

**Comment by d235j** [comment] 2016-05-20 17:43
As far as I am aware the video tracker still needs porting, that's been tracked at #339. However, this crash should not happen in any case.

**Comment by cobbchaseRazer** [comment] 2016-05-20 17:57
I don't have the tracker plugged in, for what its worth.

**Comment by rpavlik** [comment] 2016-05-21 03:41
The regex error is a dupe of a recent issue, apparently gcc 4.8 includes the regex header but it errors at runtime every time, so the associated code just needs to be tweaked to not use a regex (it's not a complicated regex)

**Comment by rpavlik** [comment] 2016-05-21 03:50
Ah, found it, this is the regex issue: https://github.com/OSVR/OSVR-Core/issues/416

**Closed** 2016-05-21 03:50 UTC
