### ISSUE TITLE
Segmentation fault 11

### ISSUE THREAD

**Issue by Such1337Hax0r** [OSVR/OSVR-Core#347] opened 2016-02-04 01:16 UTC
After compiling the latest version I ran and got this output:
"[OSVR Server] Using config file 'Test.json'
[OSVR Server] Constructing server as configured...
[OSVR Server] Loading auto-loadable plugins...
Segmentation fault: 11"
EDIT: I'm on a mac

**Comment by rpavlik** [comment] 2016-02-05 00:33
Sorry, without additional details this is hard to diagnose. What platform is this on (Mac? Linux? What distribution? What processor architecture? Etc)? Try rebuilding in RelWithDebInfo mode and getting a back trace with symbols if it crashes (run in gdb, command bt after segfault) and posting that here as well, since that will hopefully pinpoint what exactly is segfaulting - the messages shown don't narrow it down much right now.

**Comment by rpavlik** [comment] 2016-02-05 00:33
Ah, on a Mac, this is likely to be a dupe of #321 if you aren't using homebrew to build.

**Closed** 2016-02-06 20:18 UTC
